# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSd0JWqJA_F8hoE6JW3bKEOjSOXlMLtB
"""

import google.generativeai as genai

genai.configure(api_key="AIzaSyCqZiA0pNqc52G7BZiSW2MkEtk_s7pa85U")

model = genai.GenerativeModel(model_name="gemini-pro")

response = model.generate_content("Tell me a story about a magic backpack.")

print(response.text)

model = genai.GenerativeModel("gemini-pro")
chat = model.start_chat(history=[])
response = chat.send_message("Explain deep learning to young child / in one sentence")
print(response.text)

response = chat.send_message("Okay, how about a more detailed / to a high schooler")
print("\n", response.text)

for message in chat.history:
    print(f"{message.role}: {message.parts[0].text}\n")