# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSd0JWqJA_F8hoE6JW3bKEOjSOXlMLtB
"""

import google.generativeai as genai

genai.configure(api_key="AIzaSyCqZiA0pNqc52G7BZiSW2MkEtk_s7pa85U")

model = genai.GenerativeModel(model_name="gemini-pro")

response = model.generate_content("Tell me a story about a magic backpack.")

print(response.text)

from PIL import Image
img = Image.open("~/cat.jpg")